name: Bug Report
description: Report a bug in Testcontainers-Keycloak
labels: ["bug"]
body:
  - type: textarea
    attributes:
      label: Describe the bug
      description: Provide a clear and concise description of what the problem is.
    validations:
      required: true
  - type: input
    attributes:
      label: Version
      description: What version of Testcontainers-Keycloak are you running?
    validations:
      required: true
  - type: textarea
    attributes:
      label: Expected behavior
      description: Describe the expected behavior clearly and concisely.
    validations:
      required: false
  - type: textarea
    attributes:
      label: Actual behavior
      description: Describe the actual behavior clearly and concisely.
    validations:
      required: false
  - type: textarea
    attributes:
      label: How to Reproduce?
      description: |
        Provide clear and concise steps to reproduce the problem.
        Mention all configurations you made and which are important to reproduce the problem.

        If you can provide an example with which it is easy to reproduce the problem, e.g. a repository, please provide the link to it here.
        This will help best to reproduce the issue you are encountering!
    validations:
      required: false
  - type: textarea
    attributes:
      label: Relevant log output
      description: |
        Please copy and past any relevant log output (this will be automatically formatted into code).
        Please DO NOT provide screenshots/images of your log output, this is hard to read and can't be searched automatically!
      render: Shell
  - type: textarea
    attributes:
      label: Anything else?
      description: Links? References? Anything that will give us more context about the issue you are encountering!
    validations:
      required: false
