name: Enhancement Request
description: Request a new feature to be added to Testcontainers-Keycloak
labels: ["enhancement"]
body:
  - type: textarea
    attributes:
      label: Description
      description: Describe the enhancement at a high-level.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Motivation
      description: Describe why the feature should be added.
    validations:
      required: false
  - type: textarea
    attributes:
      label: Details
      description: More details? Implementation ideas? Anything that will give us more context about the enhancement you are proposing!
    validations:
      required: false
